# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.0a2.dev0+gc1c9d9b.d20230705'
__version_tuple__ = version_tuple = (0, 1, 0, 'dev0', 'gc1c9d9b.d20230705')
