name: Build and Test NLP Case Study Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test NLP Case Study Python 🐍 distributions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Git LFS
      run: |
        git lfs install --skip-repo
        git lfs pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -e .

    - name: Test with unittest
      run: python -m unittest discover tests

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*
